name: React Frontend Deployment

env:
  DOMAIN: strideton.io

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies if package files changed
        run: |
          if git diff --name-only HEAD HEAD~1 | grep -E 'package(-lock)?.json'; then
            echo "package.json or package-lock.json has changed. Running npm install."
            npm install --force
          else
            echo "No changes in package files. Skipping npm install."
          fi

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /web/${{ env.DOMAIN }}/public_html/frontend/
            rm -rf build
            echo "Preparing to deploy build files to server..."
          EOF
          
          scp -r build/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/web/${{ env.DOMAIN }}/public_html/frontend/build/
          echo "Build files uploaded to server successfully."

  move:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Move build to the server location
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /web/${{ env.DOMAIN }}/public_html/frontend/
            mv build ../build
            rm -rf build
            echo "Build has been moved to /web/${{ env.DOMAIN }}/public_html/build and cleaned up successfully."
          EOF

  notify:
    runs-on: ubuntu-latest
    needs: move

    steps:
      - name: Health Check
        run: |
          curl --fail https://strideton.io/ || exit 1
          echo "Deployment successful!"

      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Deployment complete 🚀
            ${{ github.actor }} created commit:
            Commit made by: ${{ github.event.commits[0].author.name }}
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
